/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Double.parseDouble;
import static java.lang.Thread.sleep;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import maquina.pkg2.ConverteMoeda;
import maquina.pkg2.botao;
import maquina.pkg2.conexao;
import static maquina.pkg2.conexao.statement;
import static sun.audio.AudioPlayer.player;



/**
 *
 * @author Aluno
 */
public class tela1 extends javax.swing.JFrame {

    /**
     * Creates new form tela1
     */
    public tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbpreco9 = new javax.swing.JLabel();
        lbpreco8 = new javax.swing.JLabel();
        lbpreco7 = new javax.swing.JLabel();
        lbpreco6 = new javax.swing.JLabel();
        lbpreco5 = new javax.swing.JLabel();
        lbpreco4 = new javax.swing.JLabel();
        lbpreco2 = new javax.swing.JLabel();
        lbpreco3 = new javax.swing.JLabel();
        lbpreco1 = new javax.swing.JLabel();
        lbimg8 = new javax.swing.JLabel();
        lbimg1 = new javax.swing.JLabel();
        lbimg3 = new javax.swing.JLabel();
        lbimg2 = new javax.swing.JLabel();
        lbimg6 = new javax.swing.JLabel();
        lbimg4 = new javax.swing.JLabel();
        lbimg5 = new javax.swing.JLabel();
        lbimg9 = new javax.swing.JLabel();
        lbimg7 = new javax.swing.JLabel();
        lbfundo = new javax.swing.JLabel();
        botao3 = new javax.swing.JLabel();
        botao1 = new javax.swing.JLabel();
        botao2 = new javax.swing.JLabel();
        botao6 = new javax.swing.JLabel();
        botao4 = new javax.swing.JLabel();
        botao5 = new javax.swing.JLabel();
        botao9 = new javax.swing.JLabel();
        botao7 = new javax.swing.JLabel();
        lbimg10 = new javax.swing.JLabel();
        bttroco = new javax.swing.JLabel();
        botao8 = new javax.swing.JLabel();
        lbtroco = new javax.swing.JLabel();
        lbnotas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ced20 = new javax.swing.JLabel();
        ced5 = new javax.swing.JLabel();
        ced10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbimgescolher = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbpreco9.setBackground(new java.awt.Color(255, 255, 255));
        lbpreco9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbpreco9.setOpaque(true);
        getContentPane().add(lbpreco9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 60, 20));

        lbpreco8.setBackground(new java.awt.Color(255, 255, 255));
        lbpreco8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbpreco8.setOpaque(true);
        getContentPane().add(lbpreco8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 60, 20));

        lbpreco7.setBackground(new java.awt.Color(255, 255, 255));
        lbpreco7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbpreco7.setOpaque(true);
        getContentPane().add(lbpreco7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 60, 20));

        lbpreco6.setBackground(new java.awt.Color(255, 255, 255));
        lbpreco6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbpreco6.setOpaque(true);
        getContentPane().add(lbpreco6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 60, 20));

        lbpreco5.setBackground(new java.awt.Color(255, 255, 255));
        lbpreco5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbpreco5.setOpaque(true);
        getContentPane().add(lbpreco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 60, 20));

        lbpreco4.setBackground(new java.awt.Color(255, 255, 255));
        lbpreco4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbpreco4.setOpaque(true);
        getContentPane().add(lbpreco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 60, 20));

        lbpreco2.setBackground(new java.awt.Color(255, 255, 255));
        lbpreco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbpreco2.setOpaque(true);
        getContentPane().add(lbpreco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 60, 20));

        lbpreco3.setBackground(new java.awt.Color(255, 255, 255));
        lbpreco3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbpreco3.setOpaque(true);
        getContentPane().add(lbpreco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 60, 20));

        lbpreco1.setBackground(new java.awt.Color(255, 255, 255));
        lbpreco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbpreco1.setOpaque(true);
        getContentPane().add(lbpreco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 60, 20));

        lbimg8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimg8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lbimg8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 120, 100));

        lbimg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimg1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lbimg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, 100));

        lbimg3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimg3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lbimg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 120, 100));

        lbimg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimg2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lbimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 120, 100));

        lbimg6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimg6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lbimg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 120, 100));

        lbimg4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimg4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lbimg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 120, 100));

        lbimg5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimg5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lbimg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 120, 100));

        lbimg9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimg9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lbimg9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 120, 100));

        lbimg7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimg7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lbimg7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 120, 100));

        lbfundo.setBackground(new java.awt.Color(0, 0, 0));
        lbfundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbfundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbfundo.setOpaque(true);
        getContentPane().add(lbfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 420, 380));

        botao3.setBackground(new java.awt.Color(0, 0, 0));
        botao3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botao3.setForeground(new java.awt.Color(255, 255, 255));
        botao3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botao3.setText("3");
        botao3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botao3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao3.setOpaque(true);
        botao3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao3MouseClicked(evt);
            }
        });
        getContentPane().add(botao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 70, 60));

        botao1.setBackground(new java.awt.Color(0, 0, 0));
        botao1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botao1.setForeground(new java.awt.Color(255, 255, 255));
        botao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botao1.setText("1");
        botao1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botao1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao1.setOpaque(true);
        botao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao1MouseClicked(evt);
            }
        });
        getContentPane().add(botao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 70, 60));

        botao2.setBackground(new java.awt.Color(0, 0, 0));
        botao2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botao2.setForeground(new java.awt.Color(255, 255, 255));
        botao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botao2.setText("2");
        botao2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botao2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao2.setOpaque(true);
        botao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao2MouseClicked(evt);
            }
        });
        getContentPane().add(botao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 70, 60));

        botao6.setBackground(new java.awt.Color(0, 0, 0));
        botao6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botao6.setForeground(new java.awt.Color(255, 255, 255));
        botao6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botao6.setText("6");
        botao6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botao6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao6.setOpaque(true);
        botao6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao6MouseClicked(evt);
            }
        });
        getContentPane().add(botao6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 70, 60));

        botao4.setBackground(new java.awt.Color(0, 0, 0));
        botao4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botao4.setForeground(new java.awt.Color(255, 255, 255));
        botao4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botao4.setText("4");
        botao4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botao4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao4.setOpaque(true);
        botao4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao4MouseClicked(evt);
            }
        });
        getContentPane().add(botao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 70, 60));

        botao5.setBackground(new java.awt.Color(0, 0, 0));
        botao5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botao5.setForeground(new java.awt.Color(255, 255, 255));
        botao5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botao5.setText("5");
        botao5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botao5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao5.setOpaque(true);
        botao5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao5MouseClicked(evt);
            }
        });
        getContentPane().add(botao5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 70, 60));

        botao9.setBackground(new java.awt.Color(0, 0, 0));
        botao9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botao9.setForeground(new java.awt.Color(255, 255, 255));
        botao9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botao9.setText("9");
        botao9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botao9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao9.setOpaque(true);
        botao9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao9MouseClicked(evt);
            }
        });
        getContentPane().add(botao9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 70, 60));

        botao7.setBackground(new java.awt.Color(0, 0, 0));
        botao7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botao7.setForeground(new java.awt.Color(255, 255, 255));
        botao7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botao7.setText("7");
        botao7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botao7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao7.setOpaque(true);
        botao7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao7MouseClicked(evt);
            }
        });
        getContentPane().add(botao7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 70, 60));

        lbimg10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimg10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lbimg10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 120, 100));

        bttroco.setBackground(new java.awt.Color(0, 0, 0));
        bttroco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bttroco.setForeground(new java.awt.Color(255, 255, 255));
        bttroco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bttroco.setText("TROCO");
        bttroco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bttroco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttroco.setOpaque(true);
        getContentPane().add(bttroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 210, 60));

        botao8.setBackground(new java.awt.Color(0, 0, 0));
        botao8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botao8.setForeground(new java.awt.Color(255, 255, 255));
        botao8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botao8.setText("8");
        botao8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        botao8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao8.setOpaque(true);
        botao8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao8MouseClicked(evt);
            }
        });
        getContentPane().add(botao8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 70, 60));

        lbtroco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtroco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbtroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 170, 30));

        lbnotas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbnotas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbnotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbnotasActionPerformed(evt);
            }
        });
        getContentPane().add(lbnotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 110, 30));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 70, 30));

        ced20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ced20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ced20MouseClicked(evt);
            }
        });
        getContentPane().add(ced20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 80, 40));

        ced5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ced5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ced5MouseClicked(evt);
            }
        });
        getContentPane().add(ced5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 80, 40));

        ced10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ced10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ced10MouseClicked(evt);
            }
        });
        getContentPane().add(ced10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 80, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 80, 20));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Máquina de Álbuns ");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 190, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -10, 10, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -10, 10, 40));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Selecione a quantia desejada");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 230, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -10, 10, 40));

        lbimgescolher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimgescolher.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lbimgescolher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbimgescolherMouseClicked(evt);
            }
        });
        getContentPane().add(lbimgescolher, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 120, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public double prec[] = new double[9];
    JLabel[] produto = new JLabel[9];
    JLabel[] tpreco = new JLabel[9];
int ind = 0;
String preco;
double conta = 0.0;
double total;
boolean trava = false;
 double troco = 0.0;
 ConverteMoeda conv = new ConverteMoeda();

    private void lbnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbnotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbnotasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        associaLabels();
        carregaTela();
        
         ImageIcon img = new ImageIcon(this.getClass().getResource("/img/5.jpg"));
    Image imag = img.getImage().getScaledInstance(ced5.getWidth(), ced5.getHeight(), Image.SCALE_DEFAULT);
    ced5.setIcon(new ImageIcon(imag));
    
    
        ImageIcon img1 = new ImageIcon(this.getClass().getResource("/img/10.jpg"));
    Image imag1 = img1.getImage().getScaledInstance( ced10.getWidth(),  ced10.getHeight(), Image.SCALE_DEFAULT);
    ced10.setIcon(new ImageIcon(imag1));
    
    
        ImageIcon img2 = new ImageIcon(this.getClass().getResource("/img/20.jpg"));
    Image imag2 = img2.getImage().getScaledInstance(ced20.getWidth(), ced20.getHeight(), Image.SCALE_DEFAULT);
    ced20.setIcon(new ImageIcon(imag2));
    
  
    }//GEN-LAST:event_formWindowOpened

    private void ced5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ced5MouseClicked
        // TODO add your handling code here:
      if (trava == false){
        conta = conta + 5;
        lbnotas.setText("5");
        lbnotas.setText(String.valueOf(conta));
    }//GEN-LAST:event_ced5MouseClicked
    }
    private void ced10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ced10MouseClicked
        // TODO add your handling code here:
         conta = conta + 10;
        lbnotas.setText("10");
        lbnotas.setText(String.valueOf(conta));
    }//GEN-LAST:event_ced10MouseClicked

    private void ced20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ced20MouseClicked
        // TODO add your handling code here:
        conta = conta + 20;
        lbnotas.setText("20");
        lbnotas.setText(String.valueOf(conta));
    }//GEN-LAST:event_ced20MouseClicked

    private void botao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao1MouseClicked
        // TODO add your handling code here:
        
         
        if (conta >= prec[0] && trava == false){
            troco = conta - prec[0];
            
            lbtroco.setText(String.valueOf("R$"+troco));
            
        trava = true;
        
        String caminho = "E:\\3- 2022\\DS\\3 bi\\Java\\Ferramentas\\musicas da maquina\\ultima.wav";
	botao a = new botao();
          a.Som(caminho);
         
            movimento(lbimg1);
        }else{
             JOptionPane.showMessageDialog(null, "Dinheiro insuficiente!");
        }
          ConverteMoeda conv = new ConverteMoeda();
    }//GEN-LAST:event_botao1MouseClicked
  
    private void botao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao2MouseClicked
        // TODO add your handling code here: 
        
        if (conta >= prec[1] && trava == false){
            troco = conta - prec[1];
            
            lbtroco.setText(String.valueOf("R$"+troco));
            
        trava = true;
        
        
         String caminho = "E:\\3- 2022\\DS\\3 bi\\Java\\Ferramentas\\musicas da maquina\\black-sheep.wav";
	botao b = new botao();
          b.Som(caminho);
        
         movimento(lbimg2);
         }else{
             JOptionPane.showMessageDialog(null, "Dinheiro insuficiente!");
        
    }//GEN-LAST:event_botao2MouseClicked
    }
    private void botao3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao3MouseClicked
        // TODO add your handling code here:
        
        if (conta >= prec[2] && trava == false){
            troco = conta - prec[2];
            
            lbtroco.setText(String.valueOf("R$"+troco));
            
        trava = true;
        
        
        
         String caminho = "E:\\3- 2022\\DS\\3 bi\\Java\\Ferramentas\\musicas da maquina\\na-lua.wav";
	botao p = new botao();
          p.Som(caminho);
        movimento(lbimg3);
        }else{
             JOptionPane.showMessageDialog(null, "Dinheiro insuficiente!");
        
    }//GEN-LAST:event_botao3MouseClicked
    }
    private void botao4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao4MouseClicked
        // TODO add your handling code here: 
        
        if (conta >= prec[3] && trava == false){
            troco = conta - prec[3];
            
            lbtroco.setText(String.valueOf("R$"+troco));
            
        trava = true;
        
        String caminho = "E:\\3- 2022\\DS\\3 bi\\Java\\Ferramentas\\musicas da maquina\\U.wav";
         
	botao p = new botao();
          p.Som(caminho);
         movimento(lbimg4);
         }else{
             JOptionPane.showMessageDialog(null, "Dinheiro insuficiente!");
        
    }//GEN-LAST:event_botao4MouseClicked
    }
    private void botao5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao5MouseClicked
        // TODO add your handling code here:
        if (conta >= prec[4] && trava == false){
            troco = conta - prec[4];
            
            lbtroco.setText(String.valueOf("R$"+troco));
            
        trava = true;
        
         String caminho = "E:\\3- 2022\\DS\\3 bi\\Java\\Ferramentas\\musicas da maquina\\love-like-you.wav";
	botao p = new botao();
          p.Som(caminho);
         movimento(lbimg5);
         }else{
             JOptionPane.showMessageDialog(null, "Dinheiro insuficiente!");
        
    }//GEN-LAST:event_botao5MouseClicked
    }
    private void botao6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao6MouseClicked
        // TODO add your handling code here:
        if (conta >= prec[5] && trava == false){
            troco = conta - prec[5];
            
            lbtroco.setText(String.valueOf("R$"+troco));
            
        trava = true;
        
        
        String caminho = "E:\\3- 2022\\DS\\3 bi\\Java\\Ferramentas\\musicas da maquina\\my-kind-of-woman.wav";
         
	botao p = new botao();
          p.Som(caminho);
         movimento(lbimg6);
         }else{
             JOptionPane.showMessageDialog(null, "Dinheiro insuficiente!");
        
    }//GEN-LAST:event_botao6MouseClicked
    }
    private void botao7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao7MouseClicked
        // TODO add your handling code here:
        if (conta >= prec[6] && trava == false){
            troco = conta - prec[6];
            
            lbtroco.setText(String.valueOf("R$"+troco));
            
        trava = true;
        
        
          String caminho = "E:\\3- 2022\\DS\\3 bi\\Java\\Ferramentas\\musicas da maquina\\trap-bossa-nova.wav";
         
	botao p = new botao();
          p.Som(caminho);
          movimento(lbimg7);
          }else{
             JOptionPane.showMessageDialog(null, "Dinheiro insuficiente!");
        
    }//GEN-LAST:event_botao7MouseClicked
    }
    private void botao8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao8MouseClicked
        // TODO add your handling code here: 
        
        if (conta >= prec[7] && trava == false){
            troco = conta - prec[7];
            
            lbtroco.setText(String.valueOf("R$"+troco));
            
        trava = true;
        
        
         String caminho = "E:\\3- 2022\\DS\\3 bi\\Java\\Ferramentas\\musicas da maquina\\tragic-girl.wav";
	botao p = new botao();
          p.Som(caminho);
         movimento(lbimg8);
         }else{
             JOptionPane.showMessageDialog(null, "Dinheiro insuficiente!");
        
         
    }//GEN-LAST:event_botao8MouseClicked
    }
    private void botao9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao9MouseClicked
        // TODO add your handling code here:
        if (conta >= prec[8] && trava == false){
            troco = conta - prec[8];
            
            lbtroco.setText(String.valueOf("R$"+troco));
            
        trava = true;
        
        
        String caminho = "E:\\3- 2022\\DS\\3 bi\\Java\\Ferramentas\\musicas da maquina\\sextape.wav";
        
	botao p = new botao();
          p.Som(caminho);
         movimento(lbimg9);
         }else{
             JOptionPane.showMessageDialog(null, "Dinheiro insuficiente!");
        }
        
    }//GEN-LAST:event_botao9MouseClicked

    private void lbimgescolherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbimgescolherMouseClicked
          
       
    }//GEN-LAST:event_lbimgescolherMouseClicked
 private void associaLabels()
    {
        produto[0] = lbimg1;
        produto[1] = lbimg2;
        produto[2] = lbimg3;
        produto[3] = lbimg4;
        produto[4] = lbimg5;
        produto[5] = lbimg6;
        produto[6] = lbimg7;
        produto[7] = lbimg8;
        produto[8] = lbimg9;
        
        tpreco[0] = lbpreco1;
        tpreco[1] = lbpreco2;
        tpreco[2] = lbpreco3;
        tpreco[3] = lbpreco4;
        tpreco[4] = lbpreco5;
        tpreco[5] = lbpreco6;
        tpreco[6] = lbpreco7;
        tpreco[7] = lbpreco8;
        tpreco[8] = lbpreco9;
        
        
        
          
    }
 public void movimento(final JLabel posicao){
         new Thread(){
            public void run(){ 
                 int y = posicao.getLocation().y;
                 int x = posicao.getLocation().x;
                  while(true)
                {
                    if( x < 460)
                    {
                        x = x+1; 
                        y = 190;
                        posicao.setLocation(y , x);  
                    }
                    try
                    {
                        sleep(6);
                    }
                    catch (Exception e)
                    {
                    }
                }
            }
        }.start();
       
    }
  
  private void carregaTela()
    {
       try     
       { 
        String sql = "SELECT * FROM tb01_produtos";
        
        conexao banco = new conexao();
        
        banco.conectar();
        
        ResultSet resultSet = statement.executeQuery(sql);  
        
        while (resultSet.next())
        {
          prec[ind] = parseDouble(resultSet.getString("tb01_preco"));   
          preco = resultSet.getString("tb01_preco");
          tpreco[ind].setText(conv.ConvMoeda(preco));
          
          Image img = Toolkit.getDefaultToolkit().createImage(resultSet.getBytes("tb01_img"));
          ImageIcon foto = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(produto[ind].getWidth(),produto[ind].getHeight(), Image.SCALE_DEFAULT));
          produto[ind].setIcon(foto);
         
          ind++;
        }
        
        banco.desconectar();
        resultSet.close();
        statement.close();  
        }
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botao1;
    private javax.swing.JLabel botao2;
    private javax.swing.JLabel botao3;
    private javax.swing.JLabel botao4;
    private javax.swing.JLabel botao5;
    private javax.swing.JLabel botao6;
    private javax.swing.JLabel botao7;
    private javax.swing.JLabel botao8;
    private javax.swing.JLabel botao9;
    private javax.swing.JLabel bttroco;
    private javax.swing.JLabel ced10;
    private javax.swing.JLabel ced20;
    private javax.swing.JLabel ced5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbfundo;
    private javax.swing.JLabel lbimg1;
    private javax.swing.JLabel lbimg10;
    private javax.swing.JLabel lbimg2;
    private javax.swing.JLabel lbimg3;
    private javax.swing.JLabel lbimg4;
    private javax.swing.JLabel lbimg5;
    private javax.swing.JLabel lbimg6;
    private javax.swing.JLabel lbimg7;
    private javax.swing.JLabel lbimg8;
    private javax.swing.JLabel lbimg9;
    private javax.swing.JLabel lbimgescolher;
    private javax.swing.JTextField lbnotas;
    private javax.swing.JLabel lbpreco1;
    private javax.swing.JLabel lbpreco2;
    private javax.swing.JLabel lbpreco3;
    private javax.swing.JLabel lbpreco4;
    private javax.swing.JLabel lbpreco5;
    private javax.swing.JLabel lbpreco6;
    private javax.swing.JLabel lbpreco7;
    private javax.swing.JLabel lbpreco8;
    private javax.swing.JLabel lbpreco9;
    private javax.swing.JLabel lbtroco;
    // End of variables declaration//GEN-END:variables
}
